server:
  port: 8081
spring:
  application:
    name: IGsystem
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/igsystem
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  resources:
    static-locations: classpath:/static/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
logging:
  level:
    com.IGsystem: debug
    org.springframework: DEBUG
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"


IG:
  db:
    host: localhost
    pw: 123456
  path: E:\Java-code\images
  QuestionImgPath: E:\代码实现\计设\Intelligent-Guidance-System-main\Intelligent-Guidance-System-main\src\main\resources\static\image

flask:
  host: localhost
